// <auto-generated />
using Elev99.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Elev99.Migrations
{
    [DbContext(typeof(Elev99Context))]
    [Migration("20200922214623_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Elev99.Models.CollectedData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Elevator");

                    b.Property<int>("Floor");

                    b.Property<string>("Shift");

                    b.HasKey("Id");

                    b.ToTable("CollectedData");
                });
#pragma warning restore 612, 618
        }
    }
}
